%
(Generated by SketchUcam V1.4a-7e8d3)
(File: Timbre de puerta PP19 bottom.skp)
(Bit diameter: 3,2mm)
(Feed rate: 400,0mm/min)
(Plunge Feed rate: 200,0mm/min)
(Material Thickness: 3,0mm)
(Material length: 125,0mm X width: 70,0mm)
(Overhead Gantry: false)
(Multipass enabled, Depth = 0,8mm)
(Plunge Depth first)
(Optimization is ON)
(www.PhlatBoyz.com)
G90 G21 G49  G17
M3 S400
G00 Z3.200
G00 X0 Y0 (home)
M05
M30
%
